config/routes.rb
NojukuCom::Application.routes.draw do
  devise_for :users, :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks" 
  }

  resources :spots do
    resources :reviews,   :only => [:show, :create, :destroy, :new, :index] do
      resources :thumbups,  :only => [:create, :destroy]
    end
    resources :favorites, :only => [:create, :destroy] do
      collection do
        get 'ranking', to: 'favorites#ranking'       
      end
    end
  end

  match '/about', to: 'pages#about', via: 'get'
  get "pages/contact"
  root to: 'pages#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :spot
#  has_many   :thumb_up
  validates :title,   presence: true
  validates :content, presence: true
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  has_many   :reviews, :dependent => :destroy
  belongs_to :user
  validates  :name, presence: true
  validates  :lat, numericality: true
  validates  :lng, numericality: true

  # uploaderの設定
  mount_uploader :image, ImageUploader

end

app/models/thumbup.rb
class Thumbup < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_many :spots
  has_many :reviews

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:     auth.extra.raw_info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         password: Devise.friendly_token[0,20]
                        )
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end
 
  def self.create_unique_email
    User.create_unique_string + "@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  def index
    @reviews = Review.all
  end

  def show
  end

  def new
    @review = current_user.reviews.build(spot_id: params[:spot_id])
  end

  def edit
  end

  def create
    @review = current_user.reviews.build(review_params)
    @review.spot_id = params['spot_id']

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:title, :content, :user_id, :spot_id, :score_conf, :score_safe, :score_stf)
    end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
  end

  # GET /spots/new
  def new
    @spot = current_user.spots.build
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = current_user.spots.build(spot_params)

    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render action: 'show', status: :created, location: @spot }
      else
        format.html { render action: 'new' }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spot_params
      params.require(:spot).permit(:name, :description, :lat, :lng, :image)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
    def correct_user?(spot)
       spot.user == current_user
    end
end

app/views/layouts/application.html.erb
<!--
*************************************
Template designed by Austin Gregory of
AwfulMedia.com. Before using or modifying this file
please read the included license
*************************************
Date: 6/7/2012
Author: Austin Gregory
Website: AwfulMedia.com
*************************************
-->

<!DOCTYPE html>
<html>
<head>
  <title>Nojuku.com</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="ico/apple-touch-icon-57-precomposed.png">
  <link href='http://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/"><span class="color-highlight">N</span>ojuku.com</a>
        <div class="nav-collapse">
          <ul class="nav pull-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to 'スポット', spots_path %></li>
            <li><%= link_to 'Nojukuについて', about_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "会員登録", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

      <%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<div class="nojuku-about">
		<h1 class="poem">Nojuku.comについて</h1>
		<p class="poem">
		<br /><br />
		みなさん考えた事はありますか？<br /><br />		

		自分には家がある。そのことの意味を。<br /><br />		

		一度自分に問いかけてみて下さい。<br /><br />		

		何のために家があるのか？ 自分には本当に家が必要であるのか？<br /><br />		

		安心の保証。やすらぎの空間。などなど 人それぞれ答えはあると思います。<br /><br />		

		でも果たして本当にそうなのでしょうか？<br /><br />		

		家がないと安心出来ない。やすらげない。<br /><br />		

		<b>決してそんなことはありません。</b><br /><br />		

		まだ、皆さんが知らないだけです。<br /><br />		

		そう、家が無い生活の魅力の大きさを。<br /><br />		

		そこのあなた、いつまでも家で満足していないで、 全く新しい世界、領域に一歩を踏み出してみませんか？<br /><br />		

		きっとあなたは確信するでしょう。<br /><br />		

		<b>もはや人類は家というものを必要としなくなるということを。</b><br /><br />		

		地球に生きる全ての人に、全く新しい睡眠を。 ものもおかねもいりません。<br /><br />
		</p>

	</div>
</div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
  <div class="hero-unit top-hero" style="background-image:url(<%= asset_url("top-hero-overview.jpg") %>)">
    <div class="container">
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <h1 class="catch-copy">暮らすように、野宿しよう</h1>
      <br>
      <%= link_to '野宿スポットをみる', spots_path, :class => 'btn btn-primary btn-large' %>
    </div>
  </div>

app/views/reviews/_form.html.erb
<%= form_for(@review, url: spot_reviews_path) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, style: "width:400px;;" %>
  </div>

  <%= f.label :score_conf %><br>
    <%= f.select :score_conf, [1, 2, 3, 4, 5] %>

  <%= f.label :score_safe %><br>
  <%= f.select :score_safe, [1, 2, 3, 4, 5] %>

  <%= f.label :score_stf %><br>
  <%= f.select :score_stf, [1, 2, 3, 4, 5] %><br>

  <%= f.submit %>

<% end %>

app/views/reviews/edit.html.erb
<% if user_signed_in? %>
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>
<% end %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>Spot</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= review.content %></td>
        <td><%= review.user_id %></td>
        <td><%= review.spot_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reviews/new.html.erb
<% if user_signed_in? %>
<h1>新規レビュー投稿</h1>
<br>
<%= render 'form' %>

<% end %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Spot:</strong>
  <%= @review.spot_id %>
</p>

<%= link_to 'Back', reviews_path %>

app/views/spots/_form.html.erb
<%= form_for(@spot) do |f| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br />

  <%= f.label 'スポットの名前' %>
  <%= f.text_field :name %>

  <%= f.label 'スポットの詳細' %>
  <%= f.text_area :description %><br>

  <label for="address">住所</label>
  <input type='text' name='address'><br>

  <%= f.hidden_field :lat %>

  <%= f.hidden_field :lng %><br>

  <%= f.label 'イメージ画像'  %>
  <%= f.file_field :image %><br><br>

  <%= f.submit 'スポットを登録する' ,class: 'btn' %>
<% end %>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;max-width: initial;max-width: unset;'></div>
</div>
<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  handler.map.centerOn([<%= Settings.center.lat.to_s %>, <%= Settings.center.lng.to_s %>]);
  handler.getMap().setZoom(4);
});
$("input[name=address]").change(function(){
  var address = $(':text[name="address"]').val();
  var geocoder = new google.maps.Geocoder();
  geocoder.geocode({
    address: address
  },
  function(data, status){
    if (status == google.maps.GeocoderStatus.OK) {
      var lat = data[0].geometry.location.lat()
      var lng = data[0].geometry.location.lng()
      $("#spot_lat").val(lat);
      $("#spot_lng").val(lng);

      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        handler.map.centerOn([lat, lng]);
          markers = handler.addMarkers([
            {
              "lat": lat,
              "lng": lng
            }
          ]);
          handler.bounds.extendWith(markers);
          handler.getMap().setZoom(15);
      });
    }
  });
});
</script>

app/views/spots/edit.html.erb
<div class="container">
<% if user_signed_in? %>
<h1>Editing spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>
<% end %>
</div>

app/views/spots/index.html.erb
<div class="container">
<h1>野宿スポット一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @spots.each do |spot| %>
      <tr>
        <td><%= link_to spot.name, spot %></td>
        <td><%= link_to 'スポットの編集', edit_spot_path(spot) %></td>
        <td><%= link_to '削除', spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="general_spot">
    <% @spots.each do |spot| %>
    <div class="span4">
    <div class="spot">
    <ul class="thumbnails">
        <li class="span4">
            <div class="thumbnail">
                <%= image_tag spot.image_url.to_s  %>
                <img data-src="holder.js/300x200" alt="">
                <h3><%= link_to spot.name, spot %></h3>
                <p><%= spot.description  %></p>
                <% if correct_user?(spot) %>
                   <p><%= link_to 'スポットの編集', edit_spot_path(spot) %> </p>
                   <p><%= link_to '削除', spot, method: :delete, data: { confirm: 'Are you sure?' } %></p>
                <% end %>
            </div>
        </li>
    </ul>
    </div>
    </div>
    <% end %>
</div>

<div class="span12">
<%= link_to '新しい野宿スポットを掲載する', new_spot_path %>
</div>

app/views/spots/new.html.erb
<div class="container">
<% if user_signed_in? %>
<h1>New spot</h1>

<%= render 'form' %>

<%= link_to '戻る', spots_path %>
<% end %>

</div>

app/views/spots/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h2><%= @spot.name %></h2>
<p><%= @spot.description %></p>

<div id="map" style='width: 100%; height: 400px;max-width: initial;max-width: unset;'></div>

<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @spot.lat %>,
      "lng": <%= @spot.lng %>
    }
  ]);
  handler.map.centerOn([<%= @spot.lat %>, <%= @spot.lng %>]);
  handler.bounds.extendWith(markers);
  handler.getMap().setZoom(16);
});
</script>

<%= link_to 'スポットを編集する', edit_spot_path(@spot) %> |
<%= link_to 'スポット一覧に戻る', spots_path %>
</div>